# SPDX-FileCopyrightText: 2024 Christina Sørensen
# SPDX-License-Identifier: EUPL-1.2
accepted = [
  "MIT",
  "Apache-2.0",
  "MPL-2.0",
  "Unicode-3.0",
  "BSD-3-Clause",
  "Zlib",
  "ISC",
  "CDLA-Permissive-2.0",
  "Unicode-3.0",
  "BlueOak-1.0.0",
  #"Apache-2.0 WITH LLVM-exception",
]
