# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2025 yonasBSD

[build]
rustflags = ["--cfg", "tokio_unstable"]

[profile.release]
lto = "off"
debug = "none"
opt-level = 0
strip = true

[profile.release.package."*"]
opt-level = 0

[alias]
xtask = "run --package xtask --"

[registries.crates-io]
protocol = "sparse"
