name: Linting

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:

  fmt:
    name: Rustfmt and treefmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mozilla-actions/sccache-action@v0.0.9

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --version
      - run: cargo fmt --all --check

      - name: treefmt
        run: |
          curl -s https://api.github.com/repos/numtide/treefmt/tags | jq -r '.[0].name' > .ver
          curl -sSLo treefmt.tgz https://github.com/numtide/treefmt/releases/download/$(cat .ver)/treefmt_$(cat .ver | cut -d'v' -f2)_linux_amd64.tar.gz
          tar -xvf treefmt.tgz
          ./treefmt

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mozilla-actions/sccache-action@v0.0.9

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
          name: Clippy Output

  conventional_commits:
    name: Check conventional commit compliance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Conventional commit check
        uses: cocogitto/cocogitto-action@main

  spellchecking:
    name: Spell checking and corrections
    runs-on: ubuntu-latest

    steps:
      - name: Writes changes in the local checkout
        uses: crate-ci/typos@master
        with:
          files: ./backpack/**/*.rs
          write_changes: true

      - name: Create GitHub code review suggestions
        uses: getsentry/action-git-diff-suggestions@main
        with:
          message: spell-checker
